### ISSUE TITLE
People pages with no content don't get the right "default" template

### ISSUE THREAD

**Issue by briancroxall** [Brown-University-Library/onepress-cds#3]
See [this example of Carlos](https://worfdev.services.brown.edu/create/cds/people/carlos-rotger/) or this [one of James](https://worfdev.services.brown.edu/create/cds/people/james-murdock/).

**Comment by prashleigh** [comment]
It appears that the page looks borked until you fill in the right content - then it looks fine.

I've changed the content for Carlos and the other students so that it looks fine -- but some of the alumni also need to be updated: Jean Bauer, Sam Franklin, Liz Glass, Tru Narla, Lloyd Kevin Sy

Just copy over the fake content from Carlos

**Comment by prashleigh** [comment]
New to-do list: Copy Carlos content over to

- [ ] Jean Bauer
- [ ] Sam Franklin
- [ ] Liz Glass
- [ ] Tru Narla
- [ ] Lloyd Kevin Sy

**Comment by briancroxall** [comment]
But isn't the fact that an empty page looks borked a problem that needs to be fixed? (Probably not as there should be no empty pages.) But...weird.

**Comment by emylonas** [comment]
checked the names listed above and spot checked others. Seem ok. closing
